package com.ericsson.research.iot.citypulse;

/**
 * Created by eathkar on 27/10/14.
 */
public class CityPulseConstants{

    public static boolean DEBUG = true;

    public static int VALUE_TYPE_INTEGER = 1;
    public static int VALUE_TYPE_DOUBLE = 2;

    public static int PERIODICITY_MEASUREMENT_MIN = 1;
    public static int PERIODICITY_MEASUREMENT_SEC = 2;
    public static int PERIODICITY_MEASUREMENT_MSEC = 3;

    public static int GENERATION_TYPE_RANDOM = 1;

    public static int OUTPUT_MODE_STDOUT = 1;
    public static int OUTPUT_MODE_FILE = 2;

    public static int PLAYBACK_MODE_STDOUT = 3;
    public static int PLAYBACK_MODE_NETWORK = 1;
    public static int PLAYBACK_MODE_UDP = 2;

    public static String predicateSAOValue = "http://purl.oclc.org/NET/sao/value";
    public static String predicateSAOTime = "http://purl.oclc.org/NET/sao/time";
    public static String predicateGetTimeInstant = "http://purl.org/NET/c4dm/timeline.owl#at";

    public static String[] UOM_VALUES =
            {"http://purl.oclc.org/NET/muo/ucum/unit/length/meter",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/second",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/gram",
                    "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/radian",
                    "http://purl.oclc.org/NET/muo/ucum/unit/temperature/Kelvin",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-charge/Coulomb",
                    "http://purl.oclc.org/NET/muo/ucum/unit/luminous-intensity/candela",
                    "http://purl.oclc.org/NET/muo/ucum/unit/number/the-number-ten-for-arbitrary-powers-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/number/the-number-ten-for-arbitrary-powers-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/number/the-number-pi",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fraction/percent",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fraction/parts-per-thousand",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fraction/parts-per-million",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fraction/parts-per-billion",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fraction/parts-per-trillion",
                    "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-substance/mole",
                    "http://purl.oclc.org/NET/muo/ucum/unit/solid-angle/streadian",
                    "http://purl.oclc.org/NET/muo/ucum/unit/frequency/Herz",
                    "http://purl.oclc.org/NET/muo/ucum/unit/force/Newton",
                    "http://purl.oclc.org/NET/muo/ucum/unit/pressure/Pascal",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/Joule",
                    "http://purl.oclc.org/NET/muo/ucum/unit/power/Watt",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-current/Ampere",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-potential/Volt",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-capacitance/Farad",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-resistance/Ohm",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-conductance/Siemens",
                    "http://purl.oclc.org/NET/muo/ucum/unit/magentic-flux/Weber",
                    "http://purl.oclc.org/NET/muo/ucum/unit/temperature/degree-Celsius",
                    "http://purl.oclc.org/NET/muo/ucum/unit/magnetic-flux-density/Tesla",
                    "http://purl.oclc.org/NET/muo/ucum/unit/inductance/Henry",
                    "http://purl.oclc.org/NET/muo/ucum/unit/luminous-flux/lumen",
                    "http://purl.oclc.org/NET/muo/ucum/unit/illuminance/lux",
                    "http://purl.oclc.org/NET/muo/ucum/unit/radioactivity/Becquerel",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy-dose/Gray",
                    "http://purl.oclc.org/NET/muo/ucum/unit/dose-equivalent/Sievert",
                    "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/gon",
                    "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/degree",
                    "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/minute",
                    "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/second",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/liter-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/liter-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/are",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/minute",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/hour",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/day",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/mean-Julian-year",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/mean-Gregorian-year",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/year",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/week",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/synodal-month",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/mean-Julian-month",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/mean-Gregorian-month",
                    "http://purl.oclc.org/NET/muo/ucum/unit/time/month",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/tonne",
                    "http://purl.oclc.org/NET/muo/ucum/unit/pressure/bar",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/unified-atomic-mass-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/electronvolt",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/astronomic-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/parsec",
                    "http://purl.oclc.org/NET/muo/ucum/unit/velocity/velocity-of-light",
                    "http://purl.oclc.org/NET/muo/ucum/unit/action/Planck-constant",
                    "http://purl.oclc.org/NET/muo/ucum/unit/unclassified/Boltzmann-constant",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-permittivity/permittivity-of-vacuum",
                    "http://purl.oclc.org/NET/muo/ucum/unit/magnetic-permeability/permeability-of-vacuum",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-charge/elementary-charge",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/electron-mass",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/proton-mass",
                    "http://purl.oclc.org/NET/muo/ucum/unit/unclassified/Newtonian-constant-of-gravitation",
                    "http://purl.oclc.org/NET/muo/ucum/unit/acceleration/standard-acceleration-of-free-fall",
                    "http://purl.oclc.org/NET/muo/ucum/unit/pressure/standard-atmosphere",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/light-year",
                    "http://purl.oclc.org/NET/muo/ucum/unit/force/gram-force",
                    "http://purl.oclc.org/NET/muo/ucum/unit/force/pound-force",
                    "http://purl.oclc.org/NET/muo/ucum/unit/lineic-number/Kayser",
                    "http://purl.oclc.org/NET/muo/ucum/unit/acceleration/Gal",
                    "http://purl.oclc.org/NET/muo/ucum/unit/force/dyne",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/erg",
                    "http://purl.oclc.org/NET/muo/ucum/unit/dynamic-viscosity/Poise",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-current/Biot",
                    "http://purl.oclc.org/NET/muo/ucum/unit/kinematic-viscosity/Stokes",
                    "http://purl.oclc.org/NET/muo/ucum/unit/flux-of-magnetic-induction/Maxwell",
                    "http://purl.oclc.org/NET/muo/ucum/unit/magnetic-flux-density/Gauss",
                    "http://purl.oclc.org/NET/muo/ucum/unit/magnetic-field-intensity/Oersted",
                    "http://purl.oclc.org/NET/muo/ucum/unit/magnetic-tension/Gilbert",
                    "http://purl.oclc.org/NET/muo/ucum/unit/lum.-intensity-density/stilb",
                    "http://purl.oclc.org/NET/muo/ucum/unit/brightness/Lambert",
                    "http://purl.oclc.org/NET/muo/ucum/unit/illuminance/phot",
                    "http://purl.oclc.org/NET/muo/ucum/unit/radioactivity/Curie",
                    "http://purl.oclc.org/NET/muo/ucum/unit/ion-dose/Roentgen",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy-dose/radiation-absorbed-dose",
                    "http://purl.oclc.org/NET/muo/ucum/unit/dose-equivalent/radiation-equivalent-man",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/inch-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/foot-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/yard-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/statute-mile",
                    "http://purl.oclc.org/NET/muo/ucum/unit/depth-of-water/fathom",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/nautic-mile-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/velocity/knot-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/square-inch",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/square-foot",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/square-yard",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/cubic-inch",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/cubic-foot",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/cubic-yard",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/board-foot",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/cord",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/mil-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/circular-mil",
                    "http://purl.oclc.org/NET/muo/ucum/unit/height-of-horses/hand",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/foot-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/yard-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/inch-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/rod-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/Gunter_s-chain-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/link-for-Gunter_s-chain-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/Ramden_s-chain",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/link-for-Ramden_s-chain",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/fathom-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/furlong",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/mile-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/acre-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/square-rod",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/square-mile",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/section",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/township",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/mil-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/inch-3",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/foot-3",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/rod-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/Gunter_s-chain-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/link-for-Gunter_s-chain-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/fathom-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/pace",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/yard-3",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/mile-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/nautic-mile-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/velocity/knot-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/area/acre-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/Queen_Anne_s-wine-gallon",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/barrel",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/quart",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/pint",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/gill",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/fluid-ounce",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/fluid-dram",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/minim",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/cord",
                    "http://purl.oclc.org/NET/muo/ucum/unit/dry-volume/bushel",
                    "http://purl.oclc.org/NET/muo/ucum/unit/dry-volume/historical-winchester-gallon",
                    "http://purl.oclc.org/NET/muo/ucum/unit/dry-volume/peck",
                    "http://purl.oclc.org/NET/muo/ucum/unit/dry-volume/dry-quart",
                    "http://purl.oclc.org/NET/muo/ucum/unit/dry-volume/dry-pint",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/tablespoon",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/teaspoon",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/cup",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/gallon",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/peck",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/bushel",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/quart",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/pint",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/gill",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/fluid-ounce",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/fluid-dram",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/minim",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/grain",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/pound-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/ounce-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/dram-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/short-hundredweight",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/long-hunderdweight",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/short-ton",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/long-ton",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/stone",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/pennyweight",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/ounce-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/pound-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/scruple",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/dram-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/ounce-3",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/pound-3",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/line",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/point",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/pica",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/Printer_s-point",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/Printer_s-pica",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/pied",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/pouce",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/ligne",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/didot",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/cicero",
                    "http://purl.oclc.org/NET/muo/ucum/unit/temperature/degree-Fahrenheit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/calorie-at-15_C",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/calorie-at-20_C",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/mean-calorie",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/international-table-calorie",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/thermochemical-calorie",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/calorie",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/nutrition-label-Calories",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/British-thermal-unit-at-39_F",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/British-thermal-unit-at-59_F",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/British-thermal-unit-at-60_F",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/mean-British-thermal-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/international-table-British-thermal-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/thermochemical-British-thermal-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/energy/British-thermal-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/power/horsepower",
                    "http://purl.oclc.org/NET/muo/ucum/unit/pressure/meter-of-water-column",
                    "http://purl.oclc.org/NET/muo/ucum/unit/pressure/meter-of-mercury-column",
                    "http://purl.oclc.org/NET/muo/ucum/unit/pressure/inch-of-water-column",
                    "http://purl.oclc.org/NET/muo/ucum/unit/pressure/inch-of-mercury-column",
                    "http://purl.oclc.org/NET/muo/ucum/unit/fluid-resistance/peripheral-vascular-resistance-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/refraction-of-a-lens/diopter",
                    "http://purl.oclc.org/NET/muo/ucum/unit/lineic-number/mesh",
                    "http://purl.oclc.org/NET/muo/ucum/unit/gauge-of-catheters/Charriere",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/drop",
                    "http://purl.oclc.org/NET/muo/ucum/unit/x-ray-attenuation/Hounsfield-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/metabolic-cost-of-physical-activity/metabolic-equivalent",
                    "http://purl.oclc.org/NET/muo/ucum/unit/homeopathic-potency/homeopathic-potency-of-decimal-series",
                    "http://purl.oclc.org/NET/muo/ucum/unit/homeopathic-potency/homeopathic-potency-of-centesimal-series",
                    "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-substance/equivalents",
                    "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-substance/osmole-of-dissolved-particles",
                    "http://purl.oclc.org/NET/muo/ucum/unit/acidity/pH",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass-fraction/gram-percent",
                    "http://purl.oclc.org/NET/muo/ucum/unit/sedimentation-coefficient/Svedberg-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/view-area-in-microscope/high-power-field",
                    "http://purl.oclc.org/NET/muo/ucum/unit/view-area-in-microscope/low-power-field",
                    "http://purl.oclc.org/NET/muo/ucum/unit/catalytic-activity/katal",
                    "http://purl.oclc.org/NET/muo/ucum/unit/catalytic-activity/Unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/arbitrary/international-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/arbitrary/arbitary-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/arbitrary/United-States-Pharmacopeia-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-anticardiolipin-IgG/GPL-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-anticardiolipin-IgM/MPL-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-anticardiolipin-IgA/APL-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-factor-VIII-inhibitor/Bethesda-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-antistreptolysin-O/Todd-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-amylase/Dye-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-amylase/Somogyi-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-phosphatase/Bodansky-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-phosphatase/King-Armstrong-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/arbitrary-biologic-activity/Kunkel-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/arbitrary-biologic-activity/Mac-Lagan-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-tuberculin/tuberculin-unit",
                    "http://purl.oclc.org/NET/muo/ucum/unit/level/neper",
                    "http://purl.oclc.org/NET/muo/ucum/unit/level/bel",
                    "http://purl.oclc.org/NET/muo/ucum/unit/pressure-level/bel-sound-pressure",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-potential-level/bel-volt",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-potential-level/bel-millivolt",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-potential-level/bel-microvolt",
                    "http://purl.oclc.org/NET/muo/ucum/unit/power-level/bel-watt",
                    "http://purl.oclc.org/NET/muo/ucum/unit/power-level/bel-kilowatt",
                    "http://purl.oclc.org/NET/muo/ucum/unit/volume/stere",
                    "http://purl.oclc.org/NET/muo/ucum/unit/length/Angstrom",
                    "http://purl.oclc.org/NET/muo/ucum/unit/action-area/barn",
                    "http://purl.oclc.org/NET/muo/ucum/unit/pressure/technical-atmosphere",
                    "http://purl.oclc.org/NET/muo/ucum/unit/electric-conductance/mho",
                    "http://purl.oclc.org/NET/muo/ucum/unit/pressure/pound-per-sqare-inch",
                    "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/circle",
                    "http://purl.oclc.org/NET/muo/ucum/unit/solid-angle/spere",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass/metric-carat",
                    "http://purl.oclc.org/NET/muo/ucum/unit/mass-fraction/carat-of-gold-alloys",
                    "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-information/bit-1",
                    "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-information/bit-2",
                    "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-information/byte",
                    "http://purl.oclc.org/NET/muo/ucum/unit/signal-transmission-rate/baud",
                    "http://purl.oclc.org/NET/muo/citypulse/unit/traffic/vehicle-count",
                    "http://purl.oclc.org/NET/muo/citypulse/unit/velocity/km-per-hour",
                    "http://purl.oclc.org/NET/muo/citypulse/unit/time/seconds",
                    "http://purl.oclc.org/NET/muo/citypulse/unit/events/eventData"
            };


    public static String OBSERVATION_URI_PREFIX = "#observations_";
    public static String FOI_URI_PREFIX = "#context_";
}